backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: "Create {{collection}} “{{slug}}”"
    update: "Update {{collection}} “{{slug}}”"
    delete: "Delete {{collection}} “{{slug}}”"
    uploadMedia: "[skip ci] Upload “{{path}}”"
    deleteMedia: "[skip ci] Delete “{{path}}”"

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    media_folder: img
    public_folder: "./img"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Author",
          name: "author",
          widget: "string",
          default: "Twoje Znamiona",
        }
      - {
          label: "Authors title",
          name: "authorsTitle",
          widget: "string",
          default: "specjalista onkologii klinicznej",
          required: false,
        }
      - {
          label: "Reading time",
          name: "readingTime",
          widget: "number",
          default: 5,
          min: 1,
        }
      - {
          label: "Publish Date",
          name: "date",
          widget: "datetime",
          date_format: "DD.MM.YYYY",
        }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Keywords", name: "keywords", widget: "list" }
      - {
          label: "Featured Post",
          name: "featuredpost",
          widget: "boolean",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "featuredimage",
          widget: image,
          required: false,
        }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
      - label: "Sourcs"
        name: "sourcs"
        required: false
        widget: "list"
        fields:
          - { label: "Label", name: "string", widget: "string" }
          - { label: "Link", name: "string", widget: "string" }
